In [2]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [23]:
import time 

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print("vectorized version:"+str(1000*(toc-tic))+"ms")

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print("for loop:"+str(1000*(toc-tic))+"ms")


vectorized version:1.9757747650146484ms
for loop:1418.9963340759277ms


In [24]:
u=np.zeros((5,1))
v=np.exp(u)
print(v)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [28]:
A=np.array([[56,0,4.4,68],[1.2,104,52,8],[1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [40]:
cal=A.sum(axis=0)
print(cal)


[ 59.  239.  155.4  76.9]


In [42]:
percentage=(100*A/cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [56]:
d=np.random.randn(5)
print(d)
print(d.shape)
print(d.T)
v=d.reshape((5,1))
print(v)

[ 0.00349657 -0.68107796  2.04900098  1.19884521  1.04172298]
(5,)
[ 0.00349657 -0.68107796  2.04900098  1.19884521  1.04172298]
[[ 0.00349657]
 [-0.68107796]
 [ 2.04900098]
 [ 1.19884521]
 [ 1.04172298]]


In [49]:
print(np.dot(d,d.T))

6.104678417327802


In [59]:
d=np.random.randn(5,1)
print(d)
print(d.T)

[[ 2.46448214]
 [-0.29202073]
 [-0.64193386]
 [-1.52362978]
 [-0.69839114]]
[[ 2.46448214 -0.29202073 -0.64193386 -1.52362978 -0.69839114]]


In [60]:
print(np.dot(d,d.T))

[[ 6.07367224 -0.71967988 -1.58203453 -3.7549584  -1.7211725 ]
 [-0.71967988  0.08527611  0.187458    0.44493149  0.20394469]
 [-1.58203453  0.187458    0.41207908  0.97806955  0.44832092]
 [-3.7549584   0.44493149  0.97806955  2.32144772  1.06408955]
 [-1.7211725   0.20394469  0.44832092  1.06408955  0.48775019]]


In [62]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[-0.05017141 -0.46781333 -0.76022985]
 [ 0.2630905   0.20297577 -0.0352193 ]
 [ 0.22841319 -0.23140921 -0.13315484]]
